site:
  title: Documentaci√≥n
  start_page: ROOT::index.adoc
  url: https://cortex-ia-com-co.github.io/docs
antora:
  extensions:
    - '@antora/lunr-extension'
content:
  edit_url: ~
  sources: 
    - url: .
      branches: HEAD
      start_path: ROOT
      edit_url: ~
    - url: .
      branches: HEAD
      start_path: user
      edit_url: ~
    - url: .
      branches: HEAD
      start_path: operator
      edit_url: ~
    - url: .
      branches: HEAD
      start_path: admin
      edit_url: ~
    - url: .
      branches: HEAD
      start_path: sudo
      edit_url: ~
    - url: .
      branches: HEAD
      start_path: developer
      edit_url: ~
    - url: .
      branches: HEAD
      start_path: integration
      edit_url: ~
asciidoc:
  attributes:
    page-component-sort-order: ROOT,user,operator,admin,sudo,developer,integration
    doctype: book
    kroki-server-url: 'https://kroki.io'
    kroki-fetch-diagram: ''
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
    - path: ui/css/custom.css
    - path: ui/js/diagram-handler.js
output:
  dir: ./build/site
  clean: true
