site:
  title: Manual del Operador - UnoSportClub
  start_page: operator::index.adoc
content:
  sources:
    - url: /home/neftaliyagua/Desarrollo/unosportclub/docs/operator
      branches: HEAD
      start_path: .
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: /home/neftaliyagua/Desarrollo/unosportclub/docs/build/operator
